name: wesme
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - ncurses=6.4
  - numexpr=2.11.0
  - openssl=3.0.17
  - pandas=2.3.1
  - pip=25.0
  - python=3.11.11
  - python-tzdata=2025.2
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - networkx==3.4.2
      - numpy==2.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - scipy==1.15.2
      - six==1.17.0
      - tzdata==2025.1
      - tqdm==4.67.1